### ISSUE TITLE
Add column for transfer/N or consolidate into C/R in Unit-Based Jobs Module

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#11]
In Unit-Based Jobs Module:

o	Add column for transfer/N or consolidate into C/R

You may need clarification from the business on this request...SP

**Comment by hconstant004** [comment]
@IT-LCEC please verify which direction the business would like to go with this item.

**Comment by IT-LCEC** [comment]
@camaroguru Can you please create a new bit column for transfer with value of true/false. Then populate this column during syn based upon the assemble unit type?

**Comment by hconstant004** [comment]
fixed #11

**Comment by IT-LCEC** [comment]
Released to production.
