### ISSUE TITLE
As-Builts form not saving correctly

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#14]
If WO as-built has all AU's marked qty zero and completed, then saved, it goes back to edit view and changes the completed back to Not Started

**Comment by nrodriguezlcec** [comment]
1/14/19 NR: Search for completed WO (5 pages), all of them have Oveall As-Built Status Not Started, LCEC Overall Inspection States - Not started, Overall Invoice Status = Not Invoice,  when I try to drill to change the status, received same pop-up message " No stakingsheet available for selected WO."

**Comment by IT-LCEC** [comment]
Released to production.
