### ISSUE TITLE
Inspection Form: Show all stations/AU feature

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#15]
In Unit-Based Jobs Module's Inspection Form:

During an inspection, add toggle switch to show all stations/AU’s vs showing only AU that can be inspected. Prevent all AU that can’t be inspected from the user able to change the status.

**Comment by hconstant004** [comment]
Please provide more details and/or wire-frame for better implementation.

**Comment by hconstant004** [comment]
fixed #15

**Comment by nrodriguezlcec** [comment]
1/14/19 NR: same issue as #14, 15,16, 21,25

**Comment by nrodriguezlcec** [comment]
Please advise WO # used to Unit this above request.

**Comment by hconstant004** [comment]
Any WO# with units can be used. I just used Test and identified 400000034 have units that can be used for testing.

**Comment by IT-LCEC** [comment]
Released to production.
