### ISSUE TITLE
UBJ: Inspection summary totals, AU with zero's not included

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#16]
In Unit-Based Jobs Module's Inspection summary totals:

o	Units Not Inspected should show all units not passed inspected including AU with zero’s and not started.

**Comment by nrodriguezlcec** [comment]
1/14/19 NR: Same data issue as #14

**Comment by nrodriguezlcec** [comment]
1/22/2019 NR: Please clarify if Totals Units is rows or units?

**Comment by nrodriguezlcec** [comment]
1/22/2019 NR: Per Scott,  add row(s) after word Unit(s)

**Comment by IT-LCEC** [comment]
Released to production.
