### ISSUE TITLE
Add inspection comments column to Unit-Based Jobs Module's as-built grid

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#17]
Add inspection comments column to Unit-Based Jobs Module's as-built grid. This way the vendor can see the reason for a rejected inspection.

**Comment by hconstant004** [comment]
Dev Complete

**Comment by nrodriguezlcec** [comment]
1/14/19 NR: same issue as #14, 15,16,17, 21,25

**Comment by IT-LCEC** [comment]
Released to production.
