### ISSUE TITLE
As-Built appealed comment

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#19]
In the Unit-Based Jobs Module, As-Built edit form:

If a user changes changes the status of rejected to appealed, the user shall be required to add a comment as to why they are appealing the previously rejected AU.

**Comment by hconstant004** [comment]
resolved #19

**Comment by hconstant004** [comment]
deployed to test

**Comment by nrodriguezlcec** [comment]
1/14/19 NR: same issue as  # 5, #6, #7, #9, #14, 15,16,17, 21,25

**Comment by nrodriguezlcec** [comment]
Vendor - change As-Built Status to Appealed - entered As-built Comment and received  (Red)As-Built comment required if the status is 'Appealed" when clicking SAVE button. Please advise if this red box should appear

**Comment by hconstant004** [comment]
> Vendor - change As-Built Status to Appealed - entered As-built Comment and received (Red)As-Built comment required if the status is 'Appealed" when clicking SAVE button. Please advise if this red box should appear

Yes. Comment is required when status is 'Appealed' as the message states.

**Comment by nrodriguezlcec** [comment]
400002960 - Inspector Rejected two AU  - As-Built Status did not go back to Not Inspected shows Completed.

**Comment by IT-LCEC** [comment]
Released to production.
