### ISSUE TITLE
Set default value of an rejected AU to Rejected

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#20]
In Unit-Based Jobs Module, As-Built Edit Form:

If an inspector rejected an AU, then the vendor edits the As-Built form, the default value of the As-built Status should be Rejected. This way if the user saves and didn't intend to change that AU, it will not get saved incorrectly as Appealed which is the current functionality.

**Comment by camaroguru** [comment]
This is a test. PB

**Comment by nrodriguezlcec** [comment]
1/14/19 NR: same issue as  # 5, 6, 7, 9, 14, 15,16,17,19 21,25

**Comment by IT-LCEC** [comment]
Released to production.
