### ISSUE TITLE
 Add station numbers to the export data table to CVS file function

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#22]
Could you add station numbers to the export data table to CVS file function. When I exported the data to a spreadsheet I saw no station numbers. We will need the numbers so when we send a job back to the crew to work on go-backs they will know what locations need attention. 

..Freddie

**Comment by hconstant004** [comment]
Development complete.

**Comment by nrodriguezlcec** [comment]
1/14/19 NR: same issue as  # 5, 6, 7, 9, 14, 15,16,17,19 21,22,25

**Comment by IT-LCEC** [comment]
Released to production.
