### ISSUE TITLE
Add auto-fit column width feature to all grids

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#23]
Can you make a change to the columns so we can auto-fit column width to all grids in the application?

..Freddie

**Comment by hconstant004** [comment]
Please provide more details. As it stand, all columns in all grids already "auto-adjust" depending on screen/browser size.

**Comment by IT-LCEC** [comment]
"While I was in the AsBuilt and inspection tab I noticed when I unselected columns the existing columns didn’t auto-fit width. It would be nice to read what’s in the column. See attached
![issue23](https://user-images.githubusercontent.com/44616786/49739494-040fbb80-fc60-11e8-9c80-52968bdaed32.png)
. " Freddie

**Comment by hconstant004** [comment]
fixed #25 columns auto-resize after toggle

**Comment by IT-LCEC** [comment]
Released to production.
