### ISSUE TITLE
UBJ: Add pay amount to a column on 

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#24]
Can you add pay amount to a column to all unit-based job grids?

..Freddie

**Comment by hconstant004** [comment]
Please provide more details.
Which grid requires the new column? Possible screenshot?

**Comment by hconstant004** [comment]
resolved #24

**Comment by nrodriguezlcec** [comment]
Herly, 
Under Unit-Based Jobs / As-Built form /Payment Amount column equals to  Desing Amount and As-Built Amount?

**Comment by IT-LCEC** [comment]
Released to production.
