### ISSUE TITLE
UBJ: Drag & Drop Column Re-order Bug

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#25]
In Unit-Based Area, Inspections Tab, issue reported by Freddie:

While I was inspecting this morning I was moving my columns around and when I grabbed the C/R column to move it and dropped it behind another column, it distorted the whole grid (see pic 1 below). I can log out and log back in and everything will look normal again but then all the units that I had approved were unapproved. It’s not a problem with this small job but if I was inspecting a large job it could be an issue especially if I had units inspected with rejections. Then I would have to re-inspect it all.

The reason I was moving the columns is that I like to see:
Units-unit description.-ab qty-des qty.
If location numbers where in a column and pay amount it would be: location number- Units-unit description.-ab qty-des qty-pay amount.

An option would be to lock the grid where we can’t move the columns but then we can’t arrange the columns how we want to see them. Another option could be to add a column with the station numbers. That way each unit would have the station number on it and it could help solve the issue with exporting the data table to CVS file where location numbers were not showing up (one of my previous request).
![issue24](https://user-images.githubusercontent.com/44616786/49761257-874b0480-fc94-11e8-9943-dd81485d82cd.jpg)

**Comment by hconstant004** [comment]
fixed #23 dragging and dropping any columns will no longer distort the grid.

**Comment by nrodriguezlcec** [comment]
1/14/19 NR: Unable to test, need to drill to Station to Drag & Drop or Re-Order. The system does not allow me to do anything on any of the data sync to Vendor Portal.  Same issue #14.

**Comment by IT-LCEC** [comment]
Released to production.
