### ISSUE TITLE
UBJ: Resubmitted previously rejected AU not able to be inspected

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#28]
**Module**: Unit-Based Jobs

User logged into vendor portal to approve a rejection (approve a previously rejected unit that contractor corrected) and vendor portal is giving me an error message. Then clicked on the new inspection button and vendor portal says no assembly unit or voucher available for inspection. 

**Error Msg:** No Assembly Unit or Vouchers available for inspection!

**WO/SO#** 400018773

**Comment by hconstant004** [comment]
@IT-LCEC Please try to replicate in current DEV or TEST environment. This is possibly a duplicate issue that's been addressed.

**Comment by hconstant004** [comment]
@kristaskalski possible duplicate. please verify that this issue has been addressed in the current build.

**Comment by nrodriguezlcec** [comment]
1/14/19 NR: same issue as #14, 16, 25

**Comment by IT-LCEC** [comment]
Released to production.
