### ISSUE TITLE
UBJ: Add new AU with Non-transfer results in a transfer

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#31]
**Module:** Unit-Based Job
**Tab:** As-Builts
**Bug:** When the user enters a new assembly unit and selects the Non-transfer option then saves, the value shown on the As-Built grid is a transfer.

**Comment by hconstant004** [comment]
Fixed #31.

**Comment by IT-LCEC** [comment]
Released to production.
