### ISSUE TITLE
UBJ - Sort the stations by integer value order instead of string-based value order

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#37]
**Module:** Unit-Based Jobs
**Tabs:** As-Built, Inspections, Invoicing
**Page:** As-Built, As-Built New/Edit, Inspection Details new/view, Invoice Details new/view

**Data Schema Changes:** None

**User Interface Changes:** 

1. Sort the stations by integer value order instead of string-based value order. For example: not 1, 11, 12, 2 - but 1, 2, 11, 12

**Comment by hconstant004** [comment]
fixed #37
