### ISSUE TITLE
Add unit popup clarification

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#5]
In Unit-Based Jobs Module's Add Unit popup:

Change the letters in add unit to plain English or add hover text or add label

**Comment by hconstant004** [comment]
resolved #5

**Comment by nrodriguezlcec** [comment]
1/14/19 NR: same issue as  # 5, #14, 15,16,17, 21,25

**Comment by IT-LCEC** [comment]
Released to production.
