### ISSUE TITLE
Unit-Based Jobs Module's Add Unit popup navigation

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#6]
In Unit-Based Jobs Module's Add Unit popup:

After adding a new unit, put the user back into edit mode

**Comment by hconstant004** [comment]
Dev Complete.

**Comment by nrodriguezlcec** [comment]
1/14/19 NR: same issue as  # 5, #6 #14, 15,16,17, 21,25

**Comment by IT-LCEC** [comment]
Released to production.
