### ISSUE TITLE
Color scheme for add unit popup in Unit-Based Jobs Module

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#7]
In Unit-Based Jobs Module's Add Unit popup:

Unit description comment is too grey, darken the color

**Comment by hconstant004** [comment]
Dev Complete.

**Comment by nrodriguezlcec** [comment]
1/14/19 NR: same issue as  # 5, #6, #7 #14, 15,16,17, 21,25

**Comment by IT-LCEC** [comment]
Released to production.
