### ISSUE TITLE
Add cost column to Unit-Based Jobs Module

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#8]
In Unit-Based Jobs Module:
o	Add cost column to all grids

**Comment by hconstant004** [comment]
Please clarify. Possible duplicate to ticket #24 ???

**Comment by hconstant004** [comment]
Confirmed. Relate to issue #24

**Comment by IT-LCEC** [comment]
This will be addressed by #24 

Leaving this issue closed.
