### ISSUE TITLE
Unit-Based Jobs Module, editing of as-builts by vendors

### ISSUE THREAD

**Issue by IT-LCEC** [ElectricCoops/VendorPortal#9]
In Unit-Based Jobs Module:

o	Permit the vendor to edit a completed as-built unit if it has not been inspected or invoiced. They can continue to edit if it was rejected by an inspector.

**Comment by hconstant004** [comment]
resolved #9 updated logic to include Completed and Ready for Inspection statuses.

**Comment by nrodriguezlcec** [comment]
1/14/19 NR: same issue as  # 5, #6, #7, #9, #14, 15,16,17, 21,25

**Comment by IT-LCEC** [comment]
Released to production.
